# Generated by Django 4.0.3 on 2022-04-22 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_alter_product_image_alter_product_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Jordan', 'Jordan'), ('Vans', 'Vans'), ('Puma', 'Puma'), ('Kappa', 'Kappa'), ('Under Armour', 'Under Armour'), ('Timberland', 'Timberland')], max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shoes'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='web.category'),
            preserve_default=False,
        ),
    ]
